name: build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest   
    name: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build --configuration Release

    - name: Publish WebApi1
      run: dotnet publish WebApi1/WebApi1.csproj --configuration Release -o WebApi1/bin/publish/

    - name: Publish WebApi2
      run: dotnet publish WebApi2/WebApi2.csproj --configuration Release -o WebApi2/bin/publish/